### ISSUE TITLE
[React] Dropdown list not absolute in page build

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [floating-ui/floating-ui#2482]
**Describe the bug**
In production build my `@floating-ui/react` component's dropdown list looses styles that would position it absolutely which results in it being and the bottom of the page.

Examples of this behaviour:
https://www.creation-ui.com/docs/components/select
https://www.creation-ui.com/docs/components/autocomplete
https://www.creation-ui.com/docs/components/popover

Styles present in local development for dropdown list:

```CSS
element.style {
    position: absolute;
    left: 0px;
    top: 0px;
    transform: translate(653px, 530px);
    will-change: transform;
    width: 188.617px;
    max-height: 500px;
    overflow-y: auto;
}
```

Styles present in prod env for dropdown list:

```CSS
element.style {
    width: 157.25px;
    max-height: 500px;
    overflow-y: auto;
}
```

**To Reproduce**
_I had no success in reproducing this in Code Sandbox_

Steps to reproduce the behaviour:
1. Go to https://github.com/creation-ui/react
2. Clone repo 
3. Install dependencies `pnpm i`
4. Run local development `pnpm start`

@floating-ui/react implementation for `Select` component is in this file:
https://github.com/creation-ui/react/blob/master/packages/creation-ui-react/src/components/select/select.tsx

**Expected behaviour**
Dropdown list should be attached to parent

**Screenshots**
Expected
<img width="947" alt="Zrzut ekranu 2023-08-6 o 13 29 31" src="https://github.com/floating-ui/floating-ui/assets/28536511/9e1ddbf7-1281-47de-b3c0-0ab6d3d71a66">

Current

https://github.com/floating-ui/floating-ui/assets/28536511/7c8fb382-191c-4f19-95d1-64e202b696f9

**Context:**
|     |                               |
|----------|------------------------------------|
| OS       | macOS 13.4.1                       |
| Browser  | Chrome                             |
| Version  | 115.0.5790.170 (arm64)             |
