### ISSUE TITLE
Unnecessary autoUpdate when content changes through animation

### ISSUE THREAD

**Issue by CreativeDive** [floating-ui/floating-ui#2922]
Since I used an animation within the content, the auto update fires even though it is not necessary. I set the duration to 2 seconds in the video so that it's easier to see what's happening. Unfortunately, I can't find a way to prevent this yet. The flip function is necessary, but it should not be used if the initial position still has enough space. I'm happy about any help.

https://github.com/floating-ui/floating-ui/assets/31563167/3bbbcd1d-6703-4f0d-9b36-7f673364e652

```js
/**
 * External dependencies
 */

import React, { 
    useRef, 
    Children,
    useState, 
    useEffect, 
    forwardRef, 
    useContext, 
    cloneElement,
    createContext, 
    isValidElement,
} from 'react';

import { 
    flip,
    arrow,  
    shift,
    offset,
    useDismiss,
    autoUpdate, 
    useFloating, 
    FloatingArrow, 
    FloatingPortal, 
    useInteractions,
    useTransitionStyles,
} from '@floating-ui/react'; // @ https://floating-ui.com/docs/react

/**
 * wphave dependencies
 */

import {
    mergeRefs,
    classNames,
    isTriggerElement
} from 'wphave-utils';

/**
 * WordPress dependencies
 */

import { __ } from '@wordpress/i18n';

/**
 * Internal dependencies
 */

import './style.css';
import Panel from '../panel';
import Button from '../button';
import Dialog from '../dialog';

/**
 * Component
 */

const PopoverContext = createContext();

const PopoverComponent = forwardRef((props, ref) => {

    const { 
        children,
        className,
        useArrow = true,
        popoverOffset = 10,
        setOpen,
        initialOpen = false,
        onOpenStateChange,
        placeCentered = false,
        autoUpdateSettings = {
            layoutShift: true,
            elementResize: true,
            ancestorScroll: true,
            ancestorResize: true
        },
        popoverStrategy = 'fixed',
        confirmClosingPopover = false,
        confirmClosingTitle = __('Closing', 'wphave'),
        confirmClosingMessage = __('Do you really want to close this popover?', 'wphave'),
    } = props;

    const arrowRef = useRef(null); // Popover arrow
    const referenceRef = useRef(null); // Popover button
    const floatingRef = useRef(null); // Popover content
    const [isOpen, setIsOpen] = useState(initialOpen);
    const [closingConfirmed, setClosingConfirmed] = useState(false);
    const [initialPlacement, setInitialPlacement] = useState(null);
    
    useEffect(() => {
        if (onOpenStateChange) {
            // Send the current opened state
            onOpenStateChange(isOpen);
        }
    }, [isOpen]);

    useEffect(() => {
        // Effect to provide a way to switch the opened state from external
        if (setOpen !== undefined && setOpen !== isOpen) {
            setIsOpen(setOpen);
        }
    }, [setOpen]);

    /*useEffect(() => {
        if (!confirmClosingPopover) {
            // Make sure the popover closes when you click on an iframe
            const handleBlur = () => {
                setIsOpen(false);
            };
        
            if (isOpen) {
                window.addEventListener('blur', handleBlur);
            }
        
            return () => {
                window.removeEventListener('blur', handleBlur);
            };
        }
    }, [isOpen]);*/

    const floatingAutoUpdate = (reference, floating, update) => {
        return autoUpdate(reference, floating, update, autoUpdateSettings);
    };
    
    const {refs, isPositioned, placement, context, x, y, strategy } = useFloating({
        open: isOpen,
        onOpenChange: setIsOpen,
        floating: floatingRef,
        reference: referenceRef,
        strategy: popoverStrategy,
        placement: initialPlacement || 'bottom', // <-- Preferred placement is "bottom"
        whileElementsMounted: floatingAutoUpdate,        
        middleware: [
            flip({ fallbackAxisSideDirection: 'start', fallbackStrategy: 'initialPlacement', crossAxis: false }),
            placeCentered ? offset(({rects}) => -rects.reference.height / 2 - rects.floating.height / 2) : offset(popoverOffset),             
            shift({
                padding: 35, 
                //mainAxis: 35, 
                crossAxis: 35 // Using "crossAxis" allow overlapping the floating reference
            }), // <-- ! "shift" must be placed after "flip()"
            arrow({ element: arrowRef }), // <-- ! "arrow" must be placed at last one
        ]
    });

    if (isPositioned && !initialPlacement) {
        // Save the first good placement
        setInitialPlacement(placement);
    }

    const {isMounted, styles} = useTransitionStyles(context, {
        duration: 250,
        open: { transform: 'scale(1)' },
        common: { transformOrigin: placement === 'top' ? 'bottom' : placement === 'bottom' ? 'top' : 'center' },
        close: { opacity: 0, transform: 'scale(0.8)' },
        initial: { opacity: 0, transform: 'scale(0.8)' },
    });

    console.log('styles',styles)
    const dismiss = useDismiss(context, {
        outsidePress: (event) => {
            // Define click exceptions that should prevent the popover from closing
            const exceptions = [
                '.wphave-drawer',
                '.media-modal',
                '.media-modal-content', 
            ];
            const isException = exceptions.some(selector => {
                // Do not close if inside of an exception has been clicked
                return event.target.closest(selector) != null;
            });
            // Get the current floating element and its parent
            const currentFloatingEl = refs.floating.current;
            const parentFloatingEl = refs.floating.current?.parentNode;    
            // Check if the click is outside the current floating element
            const isOutsideCurrent = currentFloatingEl && !currentFloatingEl.contains(event.target);    
            // Check if the click is outside the parent floating element
            const isOutsideParent = parentFloatingEl && !parentFloatingEl.contains(event.target);    
            // Close the popover only if the click is outside both current and parent elements
            if (isOutsideCurrent && isOutsideParent) {
                if (!isException) return true;
            }

            if (confirmClosingPopover && !closingConfirmed) return true
                
            return false;
        }
    });

    const {
        getReferenceProps, 
        getFloatingProps
    } = useInteractions([dismiss]);

    const value = { 
        x, 
        y, 
        refs, 
        styles,
        context, 
        isOpen, 
        setIsOpen, 
        strategy, 
        className, 
        arrowRef, 
        isMounted, 
        getReferenceProps, 
        getFloatingProps, 
        confirmClosingPopover, 
        setClosingConfirmed, 
        confirmClosingTitle, 
        confirmClosingMessage, 
        useArrow 
    };

    return (
        <PopoverContext.Provider value={value}>
            {children}
        </PopoverContext.Provider>
    );
});

/**
 * Trigger
 */

const PopoverTrigger = forwardRef((props, ref) => {
    
    const { 
        canOpen,
        children
    } = props;

    const triggerElement = isTriggerElement(children);
    const { refs, isOpen, setIsOpen, getReferenceProps } = useContext(PopoverContext);

    const handleTriggerClick = (e) => {
        const shouldOpen = canOpen === undefined ? true : canOpen();
        
        if (shouldOpen) {
            setIsOpen(!isOpen);
        }
    };

    const triggerProps = function(child) {
        return {
            ...child.props,
            ref: mergeRefs(refs.setReference, ref/*, parentProps?.children?.ref*/), // Set the trigger ref
            ...getReferenceProps(),
            className: classNames(
                'wphave-popover-trigger',
                isOpen ? 'opened-panel' : '',
                child.props?.className,
            ),
            onClick: (e) => {
                handleTriggerClick(e);
                if (child.props.onClick) {
                    // We have to pass the onClick event of the button trigger,
                    // in the case we want to execute the button's own action !
                    child.props.onClick(e);
                }
            }
        }
    }

    if (triggerElement) {    
        // Function to clone the children and check for the isTrigger element
        const setPropsToTriggerElement = (children) => {
            const clonedChildren = Children.map(children, (child) => {
                if (!isValidElement(child)) {
                    return child;
                }

                // If an isTrigger element is found, add the necessary props
                if (child === triggerElement) {
                    return cloneElement(child, {
                        ...child.props,
                        ...triggerProps(child) // Popover trigger element props
                    });
                }

                // If the child has other children, iterate through them recursively
                if (child.props.children) {
                    return cloneElement(child, {
                        ...child.props,
                        children: setPropsToTriggerElement(child.props.children)
                    });
                }

                // Return the unchanged child if it is not the isTrigger element
                return child;
            });

            return clonedChildren;
        };

        // If there is an element with istrigger="true", then use this preferably
        const withTriggerElement = setPropsToTriggerElement(children);
        return withTriggerElement;
    }
    
    // Otherwise, use the direct children
    const child = isValidElement(children) ? cloneElement(children, {
        ...children.props, 
        ...triggerProps(children) // Popover trigger element props
    }) : children;

    return child;
    
});

/**
* Content
*/

const PopoverContent = (props) => {

    const {
        children,
        maxWidth,
        maxHeight,
        panel = {
            title: '',
            actions: '',
        }
    } = props;

    const { className, refs, arrowRef, context, isMounted, isOpen, setIsOpen, x, y, strategy, styles, getFloatingProps, confirmClosingPopover, setClosingConfirmed, confirmClosingTitle, confirmClosingMessage, useArrow } = useContext(PopoverContext);

    const panelTitle = panel?.title;
    const panelActions = panel?.actions;
    const usePanel = panelTitle || panelActions;

    const panelOutput = (
        <Panel className="wphave-popover-panel" separated={true} scrollable={true}>
            {panelTitle && 
                <Panel.Header>
                    {panelTitle}
                </Panel.Header>
            }
            <Panel.Content>
                {children}
            </Panel.Content>
            {panelActions && 
                <Panel.Footer>
                    {panelActions}
                </Panel.Footer>
            }
        </Panel>
    );

    const defaultOutput = (
        <div className='wphave-popover-scroll' {...(maxHeight) && {style: {maxHeight: maxHeight}}}>
            {children}
            {confirmClosingPopover &&
                <Dialog>
                    <Dialog.Trigger>
                        <Button className="wphave-popover-close-button" icon="close" buttonType="icon-blank" label={__('Close', 'wphave')} />
                    </Dialog.Trigger>
                    <Dialog.Window
                        title={confirmClosingTitle}
                        requiresAction={true}
                        onConfirm={() => {
                            setClosingConfirmed(true);
                            setIsOpen(false);
                        }}>
                        {confirmClosingMessage}
                    </Dialog.Window>
                </Dialog>
            }
        </div>
    );

    const output = usePanel ? panelOutput : defaultOutput;

    return (
        isMounted && ( 
            <FloatingPortal>
                <div 
                    className={classNames('wphave-popover open wphave', className)} 
                    ref={refs.setFloating} // Set the popover ref
                    {...getFloatingProps()}
                    style={{ 
                        ...styles,
                        position: strategy || 'absolute', 
                        top: y ?? '0', 
                        left: x ?? '0',
                        ...(maxWidth && { maxWidth: maxWidth ? maxWidth : 'none' }),
                        ...(maxWidth && { minWidth: maxWidth ? maxWidth : 'none' })
                    }}>
                    {output}
                    {useArrow &&
                        <FloatingArrow 
                            ref={arrowRef} 
                            context={context} 
                            stroke="#000" 
                            strokeWidth={1} 
                            className="popover-arrow" 
                        />
                    }
                </div>
            </FloatingPortal> 
        )
    );
};

PopoverComponent.Trigger = PopoverTrigger;
PopoverComponent.Content = PopoverContent;

export default PopoverComponent;
```

```css
.wphave-popover {
    width: min-content;
    min-width: 340px;
    max-width: 400px;
    padding: 0;
    border-radius: 4px;
    background: #fff;
    box-shadow: 0 0 0 1px hsla(0, 0%, 0%, 0.1), 0 4px 11px hsla(0, 0%, 0%, 0.1), 0px 47.5085px 166.28px rgba(0, 0, 0, 0.15);
    z-index: var(--wphave-popover-level, 99999);
    color: var(--wphave-text-color);
    background: var(--wphave-bg-color);
}

.wphave-popover-scroll {
    --popover-spacing: 20px;
    display: flex;
    gap: 25px;
    flex-direction: column;
    width: auto;
    height: 100%;
    max-height: 95vh;
    padding: var(--popover-spacing);
    border-radius: 4px;
    overflow: hidden;
    overflow-y: auto;
    transition: all ease-in-out 2s;
}

.popover-arrow {
    fill: var(--wphave-bg-color);
}

.popover-arrow path[stroke] {
    stroke: hsla(0, 0%, 0%, 0.3)!important;
    stroke-width: 1;
}

/* popover trigger div ********************************/
/******************************************************/

.wphave-popover-trigger {
    width: fit-content;
}

/* popover close button *******************************/
/******************************************************/

.wphave-popover-close-button {
    position: absolute!important;
    inset: 5px 5px auto auto;
    z-index: 4;
}

/* popover backdrop ***********************************/
/******************************************************/

.popover-backdrop:before {
    content: '';
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background: rgba(255,255,255,0.5);
    backdrop-filter: blur(3px);
    z-index: 999;
}
```
